backend:
  branch: main
  name: git-gateway
collections:
- create: true
  fields:
  - label: Titre
    name: title
    widget: string
  - label: Date
    name: date
    widget: datetime
  - label: Lieu
    name: lieu
    widget: string
  - label: Heure
    name: heure
    widget: string
  - fields:
    - label: Nom
      name: nom
      widget: string
    - label: Statut
      name: statut
      options:
      - Joue
      - Disponible
      - Absent
      widget: select
    label: Joueurs
    name: joueurs
    widget: list
  folder: content/matchs
  label: Matchs
  name: matchs
  slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
media_folder: images/uploads
public_folder: /images/uploads
